### ISSUE TITLE
I have a problem after install package ConvertEmptyStringToNull issue

### ISSUE THREAD

**Issue by abdelazim94** [alkoumi/laravel-arabic-numbers#1]
After install package work fine but there is a problem that the request convert nullable value to empty string that make the application buggy please fix it.

**Comment by alkoumi** [comment]
Welcome,🤝 brother @abdelazim94 

Thank 😇 you for using my package 

I tested the package with the latest Laravel version 

It works fine 🤔, Alhamdu le Allah 

<img width="502" alt="Screen Shot 1444-02-22 at 11 33 31 AM" src="https://user-images.githubusercontent.com/10585943/190893381-419b7127-e8ab-42e2-af8d-9bae8a0512ba.png">


Maybe the error from another Bug
Happy Coding Brother
