### ISSUE TITLE
Auto-register middleware make livewire not works 

### ISSUE THREAD

**Issue by mohamedsabil83** [alkoumi/laravel-arabic-numbers#2]
After upgrading to Laravel 10, an error appears like an attached image when taking action in any livewire components.
I dig a lot until I found that the error is auto-registering the **ConvertArabicDigitsToEnlishMiddleware** middleware.

![Screenshot from 2023-06-22 20-53-16](https://github.com/alkoumi/laravel-arabic-numbers/assets/10126040/055e99c6-fc0f-453a-b5f2-826a7f10dbc3)

**Comment by itsnasser** [comment]
I get the same error, after I install the package livewire gives me errors

**Comment by binrufaid** [comment]
I have the same problem and found the reason custom Middleware 
```php
ConvertArabicDigitsToEnlishMiddleware::class
```
In this funtion  **transNumber($value)** it's return call function **str_replace** with null value of variable **$value**
```php
protected function transNumber($value)
{
    $hindi_numbers = ['٠', '١', '٢', '٣', '٤', '٥', '٦', '٧', '٨', '٩'];
    $arabic_numbers = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'];
    return str_replace($hindi_numbers, $arabic_numbers, $value);
}
```
 
A temporary solution to fix the problem:
**Go to file :** 

```php
 vendor\alkoumi\laravel-arabic-numbers\src\LaravelArabicNumbersServiceProvider.php
```
**In Function :** 
```php
 register()
```
**Under this comment: _Line number 35_** 
```php
//Auto Register The Midddleware
```
**Comment the code:**
```php
$kernel = $this->app->make(Kernel::class)
$kernel->pushMiddleware(ConvertArabicDigitsToEnlishMiddleware::class)
```
**Result**
```php
public function register()
{
  // Facade
  $this->app->singleton('numbers', function ($app) {
      return $this->app->make(Numbers::class);
  });
  
  //Auto Register The Midddleware
  //$kernel = $this->app->make(Kernel::class);
  //$kernel->pushMiddleware(ConvertArabicDigitsToEnlishMiddleware::class);
}
```

**Comment by alkoumi** [comment]
Done and tested with Laravel 10 and livewire
