### ISSUE TITLE
EURO currency not available

### ISSUE THREAD

**Issue by shazeedul** [alkoumi/laravel-arabic-numbers#4]
src/data/arab_countries.xml

In arab_countries EURO currency missing. Can you add it please?

**Comment by iqbalhasandev** [comment]
Yea. you are right . euro currency not support. throw exception.

**Comment by alkoumi** [comment]
Hellow Brothers You are welcome I am so glad for using my package

This package now supports Arabian countries only, But

I hope anyone can help me maintain this by forking the repo and making a pull request with modifications
