### ISSUE TITLE
Bangladeshi currency not supported 

### ISSUE THREAD

**Issue by iqbalhasandev** [alkoumi/laravel-arabic-numbers#5]
Hello Brother , I need Bangladeshi (BDT TAKA) currency . But This package not support Bangladeshi Currency.

**Comment by alkoumi** [comment]
Welcome Brother @iqbalhasandev , Jazaka Allahu Khairan

Actually, this package is for Arabian countries so,  you will find all Arabian countries supported only

if you can make a fork and send me a pull request to merge your modifications

I appreciate your time
